[package]
edition = "2018"

name = "kvmap_local"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonmap = "0.1"
serde_json = "1.0"
